// ALERTS
export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

// USER REGISTRATION
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

// AUTHORIZE USER
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';

// LOGIN & LOGOUT USER
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';

// CLEAR ERRORS
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

// GET PRODUCT
export const GET_PRODUCT = 'GET_PRODUCT';

// SINGLE PRODUCT
export const SINGLE_PRODUCT = 'SINGLE_PRODUCT';

// PRODUCT ERROR
export const PRODUCT_ERROR = 'PRODUCT_ERROR';

// PAGINATE
export const CHANGE_PAGE = 'CHANGE_PAGE';

// ADD TO CART
export const ADD_TO_CART = 'ADD_TO_CART';
export const CART_ERROR = 'CART_ERROR';

// CHECKOUT
export const CHECKOUT = 'CHECKOUT';
export const UPDATE_ORDER = 'UPDATE_ORDER';
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT';
export const GET_ORDERS = 'GET_ORDERS';